name: rootfs build

on:
  workflow_dispatch:
  

permissions:
  contents: write

jobs:

  rootfs-build:
  
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4
    - name: Download rootfs
      run: |
        wget -q https://github.com/termux/proot-distro/releases/download/v4.18.0/ubuntu-noble-aarch64-pd-v4.18.0.tar.xz -P $GITHUB_WORKSPACE/
    - name: Decompress rootfs
      run: |
        sudo tar -xJf ubuntu-noble-aarch64-pd-v4.18.0.tar.xz
        mv ubuntu-noble-aarch64 portadesx-2404
    - name: Mount important filesystem
      run: |
        sudo mount --bind /proc $GITHUB_WORKSPACE/portadesx-2404/proc
        sudo mount --bind /sys $GITHUB_WORKSPACE/portadesx-2404/sys
        sudo mount --bind /run $GITHUB_WORKSPACE/portadesx-2404/run
        sudo mount --bind /dev $GITHUB_WORKSPACE/portadesx-2404/dev
        sudo mount --bind /dev/pts $GITHUB_WORKSPACE/portadesx-2404/dev/pts
    - name: Install XFCE desktop and basic utility
      run: |
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "apt update && apt upgrade -y && apt install xfce4 xfce4-terminal dbus-x11 pulseaudio nano wget curl sudo adduser tigervnc-standalone-server -y && apt clean"
    - name: Adding user and password
      run: |
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo adduser --disabled-password --gecos "portadesx" portadesx && echo 'portadesx:123' | chpasswd && echo 'portadesx ALL=(ALL:ALL) ALL' >> /etc/sudoers.d/user"
    - name : Setup VNC scripts
      run: |
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "wget https://github.com/arfshl/portadesx-testing/raw/main/scripts/setupvnc.sh && sh setupvnc.sh && rm setupvnc.sh"
    - name: Remove snap apt override
      run: |
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "wget https://github.com/arfshl/no-snap-on-apt/raw/main/Noble/arm64/setup.sh && sh setup.sh && rm setup.sh"
    - name: Install user apps
      run: | 
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "apt update && apt install chromium firefox vlc thunderbird evince eog galculator libheif1 xarchiver webp-pixbuf-loader fonts-liberation p7zip -y"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo sed -i 's|chromium --incognito %U|chromium --incognito --no-sandbox %U|' /usr/share/applications/chromium.desktop"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo sed -i 's|chromium %U|chromium --no-sandbox %U|' /usr/share/applications/chromium.desktop"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo sed -i 's|chromium --new-window %U|chromium --new-window --no-sandbox %U|' /usr/share/applications/chromium.desktop"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "sudo rm /etc/chromium/master_preferences"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/firefox.desktop /home/portadesx/"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/chromium.desktop /home/portadesx/"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/vlc.desktop /home/portadesx/"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/thunderbird.desktop /home/portadesx/"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/org.gnome.Evince.desktop /home/portadesx/"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/galculator.desktop /home/portadesx/"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/org.gnome.eog.desktop /home/portadesx/"
        sudo chroot $GITHUB_WORKSPACE/portadesx-2404 /bin/bash -c "cp /usr/share/applications/xarchiver.desktop /home/portadesx/"
    - name: Unmount important filesystem
      run: |
        sudo umount -l $GITHUB_WORKSPACE/portadesx-2404/proc
        sudo umount -l $GITHUB_WORKSPACE/portadesx-2404/sys
        sudo umount -l $GITHUB_WORKSPACE/portadesx-2404/run
        sudo umount -l $GITHUB_WORKSPACE/portadesx-2404/dev
    - name: Compress rootfs
      run: |
        mkdir $GITHUB_WORKSPACE/release
        sudo tar -cJf $GITHUB_WORKSPACE/release/portadesk-2404.tar.xz $GITHUB_WORKSPACE/portadesx-2404
        echo "TIMESTAMP=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "SHA256=$(sha256sum $GITHUB_WORKSPACE/release/portadesk-2404.tar.xz | cut -d ' ' -f 1)" >> $GITHUB_ENV
    - name: Release it!
      uses: softprops/action-gh-release@v2
      with:
          tag_name: v24.04-${{ env.TIMESTAMP }}-beta
          name: Testing Release 24.04 ${{ env.TIMESTAMP }}
          body: |
            Based on Ubuntu 24.04 LTS
            Generated on ${{ env.TIMESTAMP }}
            SHA-256: `${{ env.SHA256 }}`
          draft: false
          prerelease: yes
          make_latest: false
          files: release/portadesk-2404.tar.xz
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
        
  
